baseURL = 'https://fabianobizarro.dev/blog/'
languageCode = 'pt-BR'
title = 'Blog do Bizarro'
theme = "PaperMod"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML =  true
minifyOutput = true